AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'Pods/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never
