coverage:
  status:
    project:
      shared:
        paths:
          - Sources/Shared
        threshold: 5%
      app:
        paths:
          - Sources/App
        informational: true
      pushserver:
        paths:
          - Sources/PushServer
        informational: true
    patch:
      default:
        informational: true
ignore:
  - Sources/Shared/Resources
  - Sources/App/Resources
  - Sources/SharedTesting
  - Tests
  - Pods
