import Foundation
@testable import HomeAssistant
import ObjectMapper
@testable import Shared
import Testing

@Suite(.serialized)
struct OnboardingServersListViewModelTests {
    @Test func testInitAddsSelfAsObserver() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)
        assert(sut.discoveredInstances.isEmpty)
        assert((mockBonjour.observer as? OnboardingServersListViewModel) != nil)
    }

    @Test func testStartDiscovery() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)

        sut.startDiscovery()
        assert(sut.discoveredInstances.isEmpty)
        assert(mockBonjour.startCalled)
    }

    @Test func testStopDiscovery() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)

        sut.stopDiscovery()
        assert(mockBonjour.stopCalled)
    }

    @Test func testResetFlow() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)

        sut.resetFlow()
        assert(sut.currentlyInstanceLoading == nil)
        assert(sut.manualInputLoading == false)
        assert(sut.invitationLoading == false)
    }

    @Test @MainActor func testSelectInstanceAdoptsDiscoveredInstanceIDForManualURL() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)
        // Port 1 so the authentication attempt this kicks off is refused immediately instead of
        // reaching anything; the identifier is decided before any of it runs.
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "instance-id-from-mdns",
                "internal_url": "http://127.0.0.1:1",
                "location_name": "Home",
            ],
            context: nil
        )
        sut.discoveredInstances = [discovered]

        sut.selectInstance(
            DiscoveredHomeAssistant(manualURL: URL(string: "http://127.0.0.1:1")!),
            presenter: OnboardingAuthPresenter()
        )

        #expect(sut.currentlyInstanceLoading?.uuid == "instance-id-from-mdns")
    }

    @Test @MainActor func testSelectInstanceKeepsAutogeneratedIDWhenNothingWasDiscovered() async throws {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "http://127.0.0.1:1")!)

        sut.selectInstance(manual, presenter: OnboardingAuthPresenter())

        #expect(sut.currentlyInstanceLoading?.uuid == manual.uuid)
    }

    @Test @MainActor func testOnboardingCompletionUpdatesDatabaseForServer() async {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let recorder = RecordingAppDatabaseUpdater()
        let previousUpdater = Current.appDatabaseUpdater
        Current.appDatabaseUpdater = recorder
        defer { Current.appDatabaseUpdater = previousUpdater }

        let server = Server.fake()
        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)
        sut.onboardingServer = server

        await withCheckedContinuation { continuation in
            recorder.onUpdate = { _, _ in continuation.resume() }
            sut.onboardingStateDidChange(to: .complete)
        }

        let updatedServerIds = recorder.updates.map(\.serverId)
        let usedForceUpdate = recorder.updates.allSatisfy(\.forceUpdate)
        #expect(updatedServerIds == [server.identifier.rawValue])
        #expect(usedForceUpdate)
    }

    @Test @MainActor func testOnboardingCompletionWithoutServerDoesNotUpdateDatabase() async {
        let mockBonjour = MockBonjour()
        Current.bonjour = {
            mockBonjour
        }
        let recorder = RecordingAppDatabaseUpdater()
        let previousUpdater = Current.appDatabaseUpdater
        Current.appDatabaseUpdater = recorder
        defer { Current.appDatabaseUpdater = previousUpdater }

        let sut = OnboardingServersListViewModel(shouldDismissOnSuccess: false)

        sut.onboardingStateDidChange(to: .complete)
        await withCheckedContinuation { continuation in
            DispatchQueue.main.async { continuation.resume() }
        }

        #expect(recorder.updates.isEmpty)
    }
}

private final class RecordingAppDatabaseUpdater: AppDatabaseUpdaterProtocol {
    struct Update {
        let serverId: String
        let forceUpdate: Bool
    }

    private(set) var updates: [Update] = []
    var onUpdate: ((Server, Bool) -> Void)?

    func stop() {}

    func update(server: Server, forceUpdate: Bool, showProgress _: Bool) {
        updates.append(Update(serverId: server.identifier.rawValue, forceUpdate: forceUpdate))
        onUpdate?(server, forceUpdate)
    }
}
