import Foundation
import ObjectMapper
import PromiseKit

public struct DiscoveredHomeAssistant: ImmutableMappable, Equatable {
    public static let defaultVersion = Version(major: 2022, minor: 4)

    /// Marks a `uuid` this app minted for itself because Home Assistant's own instance ID was
    /// unknown. Home Assistant publishes that ID over mDNS only (`uuid` in the zeroconf TXT record),
    /// so a server reached by a URL the user typed, or by an invitation link, starts out without it.
    public static let autogeneratedUUIDPrefix = "autogenerated-"

    /// Home Assistant's instance ID when this instance was discovered over mDNS, otherwise a
    /// locally minted `autogenerated-…` placeholder. `OnboardingAuth` turns it into the
    /// `Identifier<Server>` the onboarded server is stored under.
    public var uuid: String?
    public var version: Version?
    public var internalOrExternalURL: URL
    public var externalURL: URL?
    public var internalURL: URL?
    public var locationName: String
    public var bonjourName: String?

    public init(manualURL: URL, name: String = "Home") {
        let serverURL = manualURL.serverBaseURL()
        self.version = Self.defaultVersion
        self.uuid = "\(Self.autogeneratedUUIDPrefix)\(UUID().uuidString)"
        self.internalOrExternalURL = serverURL
        if serverURL.isLocal {
            self.internalURL = serverURL
            self.externalURL = nil
        } else {
            self.internalURL = nil
            self.externalURL = serverURL
        }
        self.locationName = name
    }

    private enum TransformError: Error {
        case missingUsableURL
    }

    public init(map: Map) throws {
        self.uuid = try map.value("uuid")
        self.version = try? map.value("version", using: VersionTransform())
        self.externalURL = try? map.value("external_url", using: URLTransform())
        self.internalURL = try? map.value("internal_url", using: URLTransform())

        if externalURL == nil, internalURL == nil {
            // compatibility with HA <0.110
            self.externalURL = try? map.value("base_url", using: URLTransform())
        }

        self.locationName = (try? map.value("location_name")) ?? "Home"

        if let url = internalURL ?? externalURL {
            self.internalOrExternalURL = url
        } else {
            throw TransformError.missingUsableURL
        }
    }

    /// Whether `uuid` is Home Assistant's own instance ID rather than a placeholder minted here.
    public var hasHomeAssistantInstanceID: Bool {
        guard let uuid, !uuid.isEmpty else { return false }
        return !uuid.hasPrefix(Self.autogeneratedUUIDPrefix)
    }

    /// Returns a copy carrying the Home Assistant instance ID of a discovered instance answering at
    /// one of the same addresses, so onboarding by typed URL or invitation link lands on the same
    /// server identifier the mDNS flow would have produced — onboarding one server through both
    /// paths then updates a single entry instead of leaving two behind.
    ///
    /// Only the identity is adopted: the URLs stay exactly as they came in, because the address the
    /// user reached the server at is the one the app has to keep talking to. Instances that already
    /// carry an instance ID, and candidates that don't, are left alone.
    public func adoptingInstanceID(from instances: [DiscoveredHomeAssistant]) -> DiscoveredHomeAssistant {
        guard !hasHomeAssistantInstanceID else { return self }

        let addresses = hostAndPortIdentities
        let match = instances.first { candidate in
            candidate.hasHomeAssistantInstanceID && !candidate.hostAndPortIdentities.isDisjoint(with: addresses)
        }

        guard let match else { return self }

        return with(self) { $0.uuid = match.uuid }
    }

    /// Every `host:port` this instance is known to answer at. The scheme is deliberately not part of
    /// it: a user reaching the same socket over `https` that mDNS advertised over `http` (or the
    /// other way around) is still the same Home Assistant.
    private var hostAndPortIdentities: Set<String> {
        let urls: [URL?] = [internalURL, externalURL, internalOrExternalURL]
        return Set(urls.compactMap { $0?.hostAndPortIdentity })
    }
}
