#!/usr/bin/env python3
"""Generate BrandIcon.swift from the logos the Home Assistant frontend bundles.

A handful of names the frontend serves under the ``mdi:`` prefix are not
Material Design Icons at all: they are SVGs the frontend ships itself, listed in
the ``CUSTOM_ICONS`` map in ``src/components/ha-icon.ts``. This script reads that
map, follows each entry to the ``src/resources/*-logo-svg.ts`` it imports, and
writes a Swift enum holding the path data so the app can draw the same logos.

Only the data lives in the generated file. Turning a path into an image is hand
written in ``BrandIcon+Image.swift``, and the grammar is parsed by ``SVGPath``.
An icon whose path uses a command ``SVGPath`` does not support is left out and
named in the generated header, so it shows up in review instead of rendering
blank.

Usage:
    Tools/BuildBrandIcons.py                 # fetch dev + regenerate
    Tools/BuildBrandIcons.py --source PATH   # parse a local frontend checkout
    Tools/BuildBrandIcons.py --check         # fail if output is stale
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

SOURCE_REPO = "https://raw.githubusercontent.com/home-assistant/frontend/dev"
ICON_COMPONENT_PATH = "src/components/ha-icon.ts"

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "Sources/HAIconic/Sources/BrandIcon.swift"

# The commands SVGPath understands; an icon using anything else is skipped.
SUPPORTED_COMMANDS = set("MLHVCZmlhvcz")

CUSTOM_ICONS_MARKER = "const CUSTOM_ICONS"
# `"music-assistant": () => import("../resources/music-assistant-logo-svg").then((mod) => mod.mdiMusicAssistant),`
ENTRY_RE = re.compile(
    r'"?(?P<name>[A-Za-z0-9_-]+)"?\s*:\s*\(\)\s*=>\s*import\(\s*"(?P<module>[^"]+)"\s*\)'
    r"\s*\.then\(\s*\([^)]*\)\s*=>\s*[A-Za-z0-9_]+\.(?P<export>[A-Za-z0-9_]+)"
)


def load_source(source: str) -> str:
    if re.match(r"^https?://", source):
        try:
            with urllib.request.urlopen(source, timeout=30) as response:  # noqa: S310 (trusted host)
                return response.read().decode("utf-8")
        except OSError as error:
            raise SystemExit(f"error: failed to fetch {source}: {error}") from error
    return Path(source).read_text(encoding="utf-8")


def resolve(base: str, path: str) -> str:
    """Where a frontend file lives, given a URL prefix or a local checkout."""
    if re.match(r"^https?://", base):
        return f"{base}/{path}"
    return str(Path(base) / path)


def custom_icons_block(text: str) -> str:
    start = text.find(CUSTOM_ICONS_MARKER)
    if start == -1:
        raise SystemExit(f"error: could not find {CUSTOM_ICONS_MARKER!r}; the source format may have changed")
    end = text.find("};", start)
    return text[start:] if end == -1 else text[start:end]


def parse_entries(block: str) -> "list[tuple[str, str, str]]":
    """Return ordered (icon name, module path, exported constant) triples."""
    flattened = re.sub(r"\s+", " ", block)
    return [(match["name"], match["module"], match["export"]) for match in ENTRY_RE.finditer(flattened)]


def path_data(base: str, module: str, export: str) -> str:
    module_path = "src/" + module.removeprefix("../")
    text = load_source(resolve(base, f"{module_path}.ts"))
    match = re.search(rf'export const {re.escape(export)}\s*=\s*"([^"]+)"', text, re.DOTALL)
    if not match:
        raise SystemExit(f"error: {export} not found in {module_path}.ts")
    return match.group(1)


def unsupported_commands(data: str) -> "set[str]":
    return {character for character in data if character.isalpha()} - SUPPORTED_COMMANDS


def swift_case(name: str) -> str:
    parts = [part for part in re.split(r"[-_]+", name) if part]
    return parts[0].lower() + "".join(part[:1].upper() + part[1:].lower() for part in parts[1:])


def render(icons: "list[tuple[str, str]]", skipped: "list[tuple[str, str]]", source: str) -> str:
    lines: list[str] = [
        "// swiftformat:disable all",
        "// Generated by Tools/BuildBrandIcons.py — DO NOT EDIT.",
        "//",
        "// Source: home-assistant/frontend",
        f"//   {source}/{ICON_COMPONENT_PATH}",
        "//",
        "// Regenerate with: Tools/BuildBrandIcons.py",
    ]
    if skipped:
        lines.append("//")
        lines.append("// Left out because SVGPath does not support every command they use:")
        for name, commands in skipped:
            lines.append(f"//   {name} ({commands})")
    lines += [
        "",
        "import Foundation",
        "",
        "/// The logos the frontend serves under the `mdi:` prefix even though Material Design Icons",
        "/// has no icon by that name, from its `CUSTOM_ICONS` map. The raw value is the icon name as",
        "/// the app normalizes it, and the path data is drawn in a 24x24 box like a glyph.",
        "public enum BrandIcon: String, CaseIterable {",
    ]
    for name, _ in icons:
        case = swift_case(name)
        raw_value = name.replace("-", "_")
        lines.append(f"    case {case}" + ("" if case == raw_value else f' = "{raw_value}"'))
    lines += [
        "",
        "    public var pathData: String {",
        "        switch self {",
    ]
    for name, data in icons:
        lines.append(f"        case .{swift_case(name)}:")
        lines.append(f'            return "{data}"')
    lines += [
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv: "list[str]") -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=SOURCE_REPO, help="URL prefix or path of a frontend checkout")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Path to the generated Swift file")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated file is out of date instead of writing it",
    )
    args = parser.parse_args(argv)

    entries = parse_entries(custom_icons_block(load_source(resolve(args.source, ICON_COMPONENT_PATH))))
    if not entries:
        print("error: no custom icons found; the source format may have changed", file=sys.stderr)
        return 1

    icons: list[tuple[str, str]] = []
    skipped: list[tuple[str, str]] = []
    for name, module, export in entries:
        data = path_data(args.source, module, export)
        unsupported = unsupported_commands(data)
        if unsupported:
            skipped.append((name, ", ".join(sorted(unsupported))))
            print(f"warning: skipping {name}, SVGPath does not support {sorted(unsupported)}", file=sys.stderr)
        else:
            icons.append((name, data))

    if not icons:
        print("error: none of the icons could be used", file=sys.stderr)
        return 1

    rendered = render(icons, skipped, args.source)
    output = Path(args.output)
    existing = output.read_text(encoding="utf-8") if output.exists() else None
    summary = f"{len(icons)} icons, {len(skipped)} skipped"

    if args.check:
        if existing == rendered:
            print(f"{output} is up to date ({summary})")
            return 0
        print(f"error: {output} is out of date; run Tools/BuildBrandIcons.py", file=sys.stderr)
        return 1

    if existing == rendered:
        print(f"{output} already up to date ({summary})")
        return 0

    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output} ({summary})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
