#if os(iOS) && !targetEnvironment(macCatalyst)
import Foundation

public extension HealthKitMetric {
    /// Food and drink intake metrics.
    static let nutritionMetrics: [HealthKitMetric] = [
        HealthKitMetric(
            uniqueID: "health_dietary_energy_consumed",
            identifier: "HKQuantityTypeIdentifierDietaryEnergyConsumed",
            name: "Dietary Energy",
            icon: "mdi:food",
            unit: "kcal",
            queryUnit: .kilocalorie,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_carbohydrates",
            identifier: "HKQuantityTypeIdentifierDietaryCarbohydrates",
            name: "Carbohydrates",
            icon: "mdi:bread-slice",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_fiber",
            identifier: "HKQuantityTypeIdentifierDietaryFiber",
            name: "Fiber",
            icon: "mdi:barley",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_sugar",
            identifier: "HKQuantityTypeIdentifierDietarySugar",
            name: "Sugar",
            icon: "mdi:cube-outline",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_protein",
            identifier: "HKQuantityTypeIdentifierDietaryProtein",
            name: "Protein",
            icon: "mdi:food-steak",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_fat_total",
            identifier: "HKQuantityTypeIdentifierDietaryFatTotal",
            name: "Total Fat",
            icon: "mdi:oil",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_fat_saturated",
            identifier: "HKQuantityTypeIdentifierDietaryFatSaturated",
            name: "Saturated Fat",
            icon: "mdi:oil",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_fat_monounsaturated",
            identifier: "HKQuantityTypeIdentifierDietaryFatMonounsaturated",
            name: "Monounsaturated Fat",
            icon: "mdi:oil",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_fat_polyunsaturated",
            identifier: "HKQuantityTypeIdentifierDietaryFatPolyunsaturated",
            name: "Polyunsaturated Fat",
            icon: "mdi:oil",
            unit: "g",
            queryUnit: .gram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_cholesterol",
            identifier: "HKQuantityTypeIdentifierDietaryCholesterol",
            name: "Cholesterol",
            icon: "mdi:oil",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_sodium",
            identifier: "HKQuantityTypeIdentifierDietarySodium",
            name: "Sodium",
            icon: "mdi:shaker-outline",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_potassium",
            identifier: "HKQuantityTypeIdentifierDietaryPotassium",
            name: "Potassium",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_calcium",
            identifier: "HKQuantityTypeIdentifierDietaryCalcium",
            name: "Calcium",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_iron",
            identifier: "HKQuantityTypeIdentifierDietaryIron",
            name: "Iron",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_magnesium",
            identifier: "HKQuantityTypeIdentifierDietaryMagnesium",
            name: "Magnesium",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_phosphorus",
            identifier: "HKQuantityTypeIdentifierDietaryPhosphorus",
            name: "Phosphorus",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_zinc",
            identifier: "HKQuantityTypeIdentifierDietaryZinc",
            name: "Zinc",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_copper",
            identifier: "HKQuantityTypeIdentifierDietaryCopper",
            name: "Copper",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_manganese",
            identifier: "HKQuantityTypeIdentifierDietaryManganese",
            name: "Manganese",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_chloride",
            identifier: "HKQuantityTypeIdentifierDietaryChloride",
            name: "Chloride",
            icon: "mdi:atom",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_chromium",
            identifier: "HKQuantityTypeIdentifierDietaryChromium",
            name: "Chromium",
            icon: "mdi:atom",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_iodine",
            identifier: "HKQuantityTypeIdentifierDietaryIodine",
            name: "Iodine",
            icon: "mdi:atom",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_molybdenum",
            identifier: "HKQuantityTypeIdentifierDietaryMolybdenum",
            name: "Molybdenum",
            icon: "mdi:atom",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_selenium",
            identifier: "HKQuantityTypeIdentifierDietarySelenium",
            name: "Selenium",
            icon: "mdi:atom",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_a",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminA",
            name: "Vitamin A",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_b6",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminB6",
            name: "Vitamin B6",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_b12",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminB12",
            name: "Vitamin B12",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_c",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminC",
            name: "Vitamin C",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_d",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminD",
            name: "Vitamin D",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_e",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminE",
            name: "Vitamin E",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_vitamin_k",
            identifier: "HKQuantityTypeIdentifierDietaryVitaminK",
            name: "Vitamin K",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_thiamin",
            identifier: "HKQuantityTypeIdentifierDietaryThiamin",
            name: "Thiamin",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_riboflavin",
            identifier: "HKQuantityTypeIdentifierDietaryRiboflavin",
            name: "Riboflavin",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_niacin",
            identifier: "HKQuantityTypeIdentifierDietaryNiacin",
            name: "Niacin",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_folate",
            identifier: "HKQuantityTypeIdentifierDietaryFolate",
            name: "Folate",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_biotin",
            identifier: "HKQuantityTypeIdentifierDietaryBiotin",
            name: "Biotin",
            icon: "mdi:pill",
            unit: "µg",
            queryUnit: .microgram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 1
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_pantothenic_acid",
            identifier: "HKQuantityTypeIdentifierDietaryPantothenicAcid",
            name: "Pantothenic Acid",
            icon: "mdi:pill",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_caffeine",
            identifier: "HKQuantityTypeIdentifierDietaryCaffeine",
            name: "Caffeine",
            icon: "mdi:coffee",
            unit: "mg",
            queryUnit: .milligram,
            aggregation: .cumulativeSum,
            category: .nutrition,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_dietary_water",
            identifier: "HKQuantityTypeIdentifierDietaryWater",
            name: "Water",
            icon: "mdi:cup-water",
            unit: "mL",
            queryUnit: .milliliter,
            aggregation: .cumulativeSum,
            category: .nutrition,
            deviceClass: .volume,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
    ]
}
#endif
