#if os(iOS) && !targetEnvironment(macCatalyst)
import Foundation

public extension HealthKitMetric {
    /// Movement, workouts and energy metrics.
    static let activityMetrics: [HealthKitMetric] = [
        HealthKitMetric(
            uniqueID: "health_distance_walking_running",
            identifier: "HKQuantityTypeIdentifierDistanceWalkingRunning",
            name: "Walking + Running Distance",
            icon: "mdi:walk",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_distance_cycling",
            identifier: "HKQuantityTypeIdentifierDistanceCycling",
            name: "Cycling Distance",
            icon: "mdi:bike",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_distance_wheelchair",
            identifier: "HKQuantityTypeIdentifierDistanceWheelchair",
            name: "Wheelchair Distance",
            icon: "mdi:wheelchair",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing
        ),
        HealthKitMetric(
            uniqueID: "health_distance_swimming",
            identifier: "HKQuantityTypeIdentifierDistanceSwimming",
            name: "Swimming Distance",
            icon: "mdi:swim",
            unit: "m",
            queryUnit: .meter,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_distance_downhill_snow_sports",
            identifier: "HKQuantityTypeIdentifierDistanceDownhillSnowSports",
            name: "Downhill Snow Sports Distance",
            icon: "mdi:ski",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            availableFromIOS: 11
        ),
        HealthKitMetric(
            uniqueID: "health_distance_cross_country_skiing",
            identifier: "HKQuantityTypeIdentifierDistanceCrossCountrySkiing",
            name: "Cross Country Skiing Distance",
            icon: "mdi:ski-cross-country",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_distance_paddle_sports",
            identifier: "HKQuantityTypeIdentifierDistancePaddleSports",
            name: "Paddle Sports Distance",
            icon: "mdi:rowing",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_distance_rowing",
            identifier: "HKQuantityTypeIdentifierDistanceRowing",
            name: "Rowing Distance",
            icon: "mdi:rowing",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_distance_skating_sports",
            identifier: "HKQuantityTypeIdentifierDistanceSkatingSports",
            name: "Skating Sports Distance",
            icon: "mdi:skate",
            unit: "km",
            queryUnit: .kilometer,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .distance,
            stateClass: .totalIncreasing,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_active_energy_burned",
            identifier: "HKQuantityTypeIdentifierActiveEnergyBurned",
            name: "Active Energy",
            icon: "mdi:fire",
            unit: "kcal",
            queryUnit: .kilocalorie,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_basal_energy_burned",
            identifier: "HKQuantityTypeIdentifierBasalEnergyBurned",
            name: "Resting Energy",
            icon: "mdi:fire",
            unit: "kcal",
            queryUnit: .kilocalorie,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_flights_climbed",
            identifier: "HKQuantityTypeIdentifierFlightsClimbed",
            name: "Flights Climbed",
            icon: "mdi:stairs-up",
            unit: "floors",
            queryUnit: .count,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_push_count",
            identifier: "HKQuantityTypeIdentifierPushCount",
            name: "Wheelchair Pushes",
            icon: "mdi:wheelchair",
            unit: "pushes",
            queryUnit: .count,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_swimming_stroke_count",
            identifier: "HKQuantityTypeIdentifierSwimmingStrokeCount",
            name: "Swimming Strokes",
            icon: "mdi:swim",
            unit: "strokes",
            queryUnit: .count,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_nike_fuel",
            identifier: "HKQuantityTypeIdentifierNikeFuel",
            name: "NikeFuel",
            icon: "mdi:run",
            unit: "points",
            queryUnit: .count,
            aggregation: .cumulativeSum,
            category: .activity,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_apple_exercise_time",
            identifier: "HKQuantityTypeIdentifierAppleExerciseTime",
            name: "Exercise Time",
            icon: "mdi:timer-outline",
            unit: "min",
            queryUnit: .minute,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .duration,
            stateClass: .totalIncreasing,
            decimalPlaces: 0
        ),
        HealthKitMetric(
            uniqueID: "health_apple_move_time",
            identifier: "HKQuantityTypeIdentifierAppleMoveTime",
            name: "Move Time",
            icon: "mdi:timer-outline",
            unit: "min",
            queryUnit: .minute,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .duration,
            stateClass: .totalIncreasing,
            decimalPlaces: 0,
            availableFromIOS: 14
        ),
        HealthKitMetric(
            uniqueID: "health_apple_stand_time",
            identifier: "HKQuantityTypeIdentifierAppleStandTime",
            name: "Stand Time",
            icon: "mdi:human-handsup",
            unit: "min",
            queryUnit: .minute,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .duration,
            stateClass: .totalIncreasing,
            decimalPlaces: 0,
            availableFromIOS: 13
        ),
        HealthKitMetric(
            uniqueID: "health_time_in_daylight",
            identifier: "HKQuantityTypeIdentifierTimeInDaylight",
            name: "Time in Daylight",
            icon: "mdi:white-balance-sunny",
            unit: "min",
            queryUnit: .minute,
            aggregation: .cumulativeSum,
            category: .activity,
            deviceClass: .duration,
            stateClass: .totalIncreasing,
            decimalPlaces: 0,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_vo2_max",
            identifier: "HKQuantityTypeIdentifierVO2Max",
            name: "VO2 Max",
            icon: "mdi:lungs",
            unit: "mL/kg·min",
            queryUnit: .milliliterPerKilogramPerMinute,
            aggregation: .mostRecent,
            category: .activity,
            stateClass: .measurement,
            lookbackDays: 365,
            decimalPlaces: 1,
            availableFromIOS: 11
        ),
        HealthKitMetric(
            uniqueID: "health_running_speed",
            identifier: "HKQuantityTypeIdentifierRunningSpeed",
            name: "Running Speed",
            icon: "mdi:run-fast",
            unit: "m/s",
            queryUnit: .meterPerSecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .speed,
            stateClass: .measurement,
            availableFromIOS: 16
        ),
        HealthKitMetric(
            uniqueID: "health_running_power",
            identifier: "HKQuantityTypeIdentifierRunningPower",
            name: "Running Power",
            icon: "mdi:run-fast",
            unit: "W",
            queryUnit: .watt,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .power,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 16
        ),
        HealthKitMetric(
            uniqueID: "health_running_stride_length",
            identifier: "HKQuantityTypeIdentifierRunningStrideLength",
            name: "Running Stride Length",
            icon: "mdi:run",
            unit: "cm",
            queryUnit: .centimeter,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .distance,
            stateClass: .measurement,
            decimalPlaces: 1,
            availableFromIOS: 16
        ),
        HealthKitMetric(
            uniqueID: "health_running_vertical_oscillation",
            identifier: "HKQuantityTypeIdentifierRunningVerticalOscillation",
            name: "Running Vertical Oscillation",
            icon: "mdi:run",
            unit: "cm",
            queryUnit: .centimeter,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .distance,
            stateClass: .measurement,
            decimalPlaces: 1,
            availableFromIOS: 16
        ),
        HealthKitMetric(
            uniqueID: "health_running_ground_contact_time",
            identifier: "HKQuantityTypeIdentifierRunningGroundContactTime",
            name: "Running Ground Contact Time",
            icon: "mdi:run",
            unit: "ms",
            queryUnit: .millisecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .duration,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 16
        ),
        HealthKitMetric(
            uniqueID: "health_cycling_speed",
            identifier: "HKQuantityTypeIdentifierCyclingSpeed",
            name: "Cycling Speed",
            icon: "mdi:bike-fast",
            unit: "m/s",
            queryUnit: .meterPerSecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .speed,
            stateClass: .measurement,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_cycling_power",
            identifier: "HKQuantityTypeIdentifierCyclingPower",
            name: "Cycling Power",
            icon: "mdi:bike-fast",
            unit: "W",
            queryUnit: .watt,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .power,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_cycling_cadence",
            identifier: "HKQuantityTypeIdentifierCyclingCadence",
            name: "Cycling Cadence",
            icon: "mdi:bike",
            unit: "rpm",
            queryUnit: .countPerMinute,
            aggregation: .mostRecent,
            category: .activity,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_cycling_functional_threshold_power",
            identifier: "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower",
            name: "Cycling Functional Threshold Power",
            icon: "mdi:bike-fast",
            unit: "W",
            queryUnit: .watt,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .power,
            stateClass: .measurement,
            lookbackDays: 365,
            decimalPlaces: 0,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_physical_effort",
            identifier: "HKQuantityTypeIdentifierPhysicalEffort",
            name: "Physical Effort",
            icon: "mdi:arm-flex",
            unit: "kcal/kg·h",
            queryUnit: .kilocaloriePerKilogramPerHour,
            aggregation: .mostRecent,
            category: .activity,
            stateClass: .measurement,
            decimalPlaces: 1,
            availableFromIOS: 17
        ),
        HealthKitMetric(
            uniqueID: "health_cross_country_skiing_speed",
            identifier: "HKQuantityTypeIdentifierCrossCountrySkiingSpeed",
            name: "Cross Country Skiing Speed",
            icon: "mdi:ski-cross-country",
            unit: "m/s",
            queryUnit: .meterPerSecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .speed,
            stateClass: .measurement,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_paddle_sports_speed",
            identifier: "HKQuantityTypeIdentifierPaddleSportsSpeed",
            name: "Paddle Sports Speed",
            icon: "mdi:rowing",
            unit: "m/s",
            queryUnit: .meterPerSecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .speed,
            stateClass: .measurement,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_rowing_speed",
            identifier: "HKQuantityTypeIdentifierRowingSpeed",
            name: "Rowing Speed",
            icon: "mdi:rowing",
            unit: "m/s",
            queryUnit: .meterPerSecond,
            aggregation: .mostRecent,
            category: .activity,
            deviceClass: .speed,
            stateClass: .measurement,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_workout_effort_score",
            identifier: "HKQuantityTypeIdentifierWorkoutEffortScore",
            name: "Workout Effort Score",
            icon: "mdi:arm-flex",
            unit: nil,
            queryUnit: .effortScore,
            aggregation: .mostRecent,
            category: .activity,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 18
        ),
        HealthKitMetric(
            uniqueID: "health_estimated_workout_effort_score",
            identifier: "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore",
            name: "Estimated Workout Effort Score",
            icon: "mdi:arm-flex",
            unit: nil,
            queryUnit: .effortScore,
            aggregation: .mostRecent,
            category: .activity,
            stateClass: .measurement,
            decimalPlaces: 0,
            availableFromIOS: 18
        ),
    ]
}
#endif
