import Foundation
import ObjectMapper
@testable import Shared
import Testing

@Suite("DiscoveredHomeAssistant Tests")
struct DiscoveredHomeAssistantTests {
    // MARK: - Manual URL Initialization Tests

    @Test("Manual URL initialization with local-like URL")
    func manualURLInitWithLocalURL() async throws {
        let localURL = URL(string: "http://192.168.1.100:8123")!
        let discovered = DiscoveredHomeAssistant(manualURL: localURL, name: "Test Home")

        #expect(discovered.uuid != nil)
        #expect(discovered.uuid?.hasPrefix("autogenerated-") == true)
        #expect(discovered.version == Version(major: 2022, minor: 4))
        #expect(discovered.internalOrExternalURL == localURL)
        #expect(discovered.locationName == "Test Home")
        #expect(discovered.bonjourName == nil)

        // The URL categorization depends on the actual isLocal implementation
        #expect(discovered.internalURL != nil || discovered.externalURL != nil)
    }

    @Test("Manual URL initialization with external URL")
    func manualURLInitWithExternalURL() async throws {
        let externalURL = URL(string: "https://example.duckdns.org:8123")!
        let discovered = DiscoveredHomeAssistant(manualURL: externalURL, name: "Remote Home")

        #expect(discovered.uuid != nil)
        #expect(discovered.uuid?.hasPrefix("autogenerated-") == true)
        #expect(discovered.version == Version(major: 2022, minor: 4))
        #expect(discovered.internalOrExternalURL == externalURL)
        #expect(discovered.locationName == "Remote Home")
        #expect(discovered.bonjourName == nil)

        // The URL categorization depends on the actual isLocal implementation
        #expect(discovered.internalURL != nil || discovered.externalURL != nil)
    }

    @Test("Manual URL initialization with default name")
    func manualURLInitWithDefaultName() async throws {
        let url = URL(string: "http://homeassistant.local:8123")!
        let discovered = DiscoveredHomeAssistant(manualURL: url)

        #expect(discovered.locationName == "Home")
    }

    @Test("Manual URL initialization removes path query and fragment but keeps port")
    func manualURLInitWithFullFrontendURL() async throws {
        let url = URL(string: "http://homeassistant.local:8123/lovelace/0?foo=bar#section")!
        let expectedURL = URL(string: "http://homeassistant.local:8123")!
        let discovered = DiscoveredHomeAssistant(manualURL: url)

        #expect(discovered.internalOrExternalURL == expectedURL)
        #expect(discovered.internalURL == expectedURL || discovered.externalURL == expectedURL)
    }

    // MARK: - Instance ID Adoption Tests

    @Test("Manually entered URL adopts the instance ID discovered at the same address")
    func manualURLAdoptsInstanceIDOfDiscoveredInstance() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "instance-id-from-mdns",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "http://192.168.1.100:8123")!)

        let adopted = manual.adoptingInstanceID(from: [discovered])

        #expect(adopted.uuid == "instance-id-from-mdns")
        #expect(adopted.hasHomeAssistantInstanceID)
        // Only the identity is adopted — the address the user reached the server at is kept.
        #expect(adopted.internalURL == manual.internalURL)
        #expect(adopted.externalURL == manual.externalURL)
        #expect(adopted.internalOrExternalURL == manual.internalOrExternalURL)
        #expect(adopted.locationName == manual.locationName)
    }

    @Test("Remote URL adopts the instance ID of the instance advertising it externally")
    func manualURLAdoptsInstanceIDMatchingExternalURL() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "instance-id-from-mdns",
                "internal_url": "http://192.168.1.100:8123",
                "external_url": "https://example.duckdns.org",
                "location_name": "Home",
            ],
            context: nil
        )
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "https://example.duckdns.org")!)

        #expect(manual.adoptingInstanceID(from: [discovered]).uuid == "instance-id-from-mdns")
    }

    @Test("Adoption ignores the scheme and fills in default ports")
    func adoptionIgnoresSchemeAndDefaultPorts() async throws {
        let plaintext = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "plaintext-instance",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let defaultPort = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "default-port-instance",
                "external_url": "https://example.duckdns.org",
                "location_name": "Home",
            ],
            context: nil
        )

        // Reached over TLS by a reverse proxy sitting on the same socket mDNS advertised.
        let overTLS = DiscoveredHomeAssistant(manualURL: URL(string: "https://192.168.1.100:8123")!)
        #expect(overTLS.adoptingInstanceID(from: [plaintext]).uuid == "plaintext-instance")

        // https://host and https://host:443 are the same address.
        let explicitPort = DiscoveredHomeAssistant(manualURL: URL(string: "https://example.duckdns.org:443")!)
        #expect(explicitPort.adoptingInstanceID(from: [defaultPort]).uuid == "default-port-instance")
    }

    @Test("Hosts compare case-insensitively")
    func adoptionNormalizesHost() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "instance-id-from-mdns",
                "internal_url": "http://HomeAssistant.local:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "http://homeassistant.local:8123")!)

        #expect(manual.adoptingInstanceID(from: [discovered]).uuid == "instance-id-from-mdns")
    }

    @Test("A different address keeps the autogenerated identifier")
    func adoptionKeepsAutogeneratedIDWhenNothingMatches() async throws {
        let otherHost = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "other-host",
                "internal_url": "http://192.168.1.101:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let otherPort = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "other-port",
                "internal_url": "http://192.168.1.100:8124",
                "location_name": "Home",
            ],
            context: nil
        )
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "http://192.168.1.100:8123")!)

        let adopted = manual.adoptingInstanceID(from: [otherHost, otherPort])

        #expect(adopted.uuid == manual.uuid)
        #expect(adopted.hasHomeAssistantInstanceID == false)
    }

    @Test("Adoption never overwrites an instance ID Home Assistant provided")
    func adoptionKeepsExistingInstanceID() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "discovered-instance",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let sameAddress = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "another-instance",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )

        #expect(discovered.adoptingInstanceID(from: [sameAddress]).uuid == "discovered-instance")
    }

    @Test("Candidates without an instance ID are not adopted from")
    func adoptionIgnoresCandidatesWithoutInstanceID() async throws {
        let url = URL(string: "http://192.168.1.100:8123")!
        let candidate = DiscoveredHomeAssistant(manualURL: url)
        let manual = DiscoveredHomeAssistant(manualURL: url)

        let adopted = manual.adoptingInstanceID(from: [candidate])

        #expect(adopted.uuid == manual.uuid)
        #expect(adopted.uuid != candidate.uuid)
    }

    @Test("An empty uuid is not treated as an instance ID")
    func emptyUUIDIsNotAnInstanceID() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )

        #expect(discovered.hasHomeAssistantInstanceID == false)
        // Nothing to adopt from, and nothing to adopt onto.
        #expect(discovered.adoptingInstanceID(from: [discovered]).uuid == "")
    }

    @Test("A URL without a usable host and port never matches")
    func adoptionIgnoresURLsWithoutHostAndPort() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "instance-id-from-mdns",
                "internal_url": "http://192.168.1.100:8123",
                "location_name": "Home",
            ],
            context: nil
        )
        let manual = DiscoveredHomeAssistant(manualURL: URL(string: "file:///config")!)

        let adopted = manual.adoptingInstanceID(from: [discovered])

        #expect(adopted.uuid == manual.uuid)
        #expect(adopted.hasHomeAssistantInstanceID == false)
    }

    @Test("mDNS payload allows missing version")
    func mdnsPayloadAllowsMissingVersion() async throws {
        let discovered = try DiscoveredHomeAssistant(
            JSON: [
                "uuid": "test-uuid",
                "internal_url": "http://homeassistant.local:8123",
                "location_name": "Test Home",
            ],
            context: nil
        )

        #expect(discovered.version == nil)
        #expect(discovered.uuid == "test-uuid")
        #expect(discovered.internalOrExternalURL == URL(string: "http://homeassistant.local:8123")!)
        #expect(discovered.locationName == "Test Home")
    }
}
