name: iOS Build Check

on:
  workflow_dispatch:
  push:
    branches: [ nameChanged ]
  pull_request:
    branches: [ nameChanged ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby (for CocoaPods, if needed)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods if Podfile exists
        run: |
          if [ -f Podfile ]; then
            gem install cocoapods || true
            pod install --repo-update || true
          fi

      - name: Detect project/workspace, scheme and build (Simulator)
        shell: bash
        run: |
          set -euo pipefail
          echo "Listing repo root files:"
          ls -la

          WORKSPACE=$(ls *.xcworkspace 2>/dev/null | head -n1 || true)
          PROJECT=$(ls *.xcodeproj 2>/dev/null | head -n1 || true)

          if [ -n "$WORKSPACE" ]; then
            echo "Found workspace: $WORKSPACE"
            SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list 2>/dev/null | sed -n '/Schemes:/,/^$/p' | sed '1d' | sed -n '1p' | xargs || true)
            if [ -z "$SCHEME" ]; then
              echo "No scheme detected from workspace. Listing content:"
              xcodebuild -workspace "$WORKSPACE" -list || true
            fi
            echo "Using scheme: $SCHEME"
            xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean build | tee xcodebuild.log
          elif [ -n "$PROJECT" ]; then
            echo "Found project: $PROJECT"
            SCHEME=$(xcodebuild -list -project "$PROJECT" 2>/dev/null | sed -n '/Schemes:/,/^$/p' | sed '1d' | sed -n '1p' | xargs || true)
            echo "Using scheme: $SCHEME"
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean build | tee xcodebuild.log
          else
            echo "ERROR: No .xcworkspace or .xcodeproj found in repo root. Cannot build."
            exit 1
          fi

      - name: Upload build logs and any .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            xcodebuild.log
            build/Build/Products/Debug-iphonesimulator/*.app
