name: iOS Build Check

on:
  workflow_dispatch:
  push:
    branches: [ nameChanged, master ]
  pull_request:
    branches: [ nameChanged, master ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Set up Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install
          pod install --repo-update

      - name: Build Debug
        run: |
          xcodebuild -workspace HomeAssistant.xcworkspace \
                     -scheme App-Debug \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
                     clean build \
                     CODE_SIGNING_ALLOWED=NO | tee xcodebuild.log

      - name: Build Release
        run: |
          xcodebuild -workspace HomeAssistant.xcworkspace \
                     -scheme App-Release \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
                     clean build \
                     CODE_SIGNING_ALLOWED=NO | tee xcodebuild-release.log

      - name: Upload build logs and artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            xcodebuild.log
            xcodebuild-release.log
            ~/Library/Developer/Xcode/DerivedData/SH-PRO-*/Build/Products/Debug-iphonesimulator/*.app
            ~/Library/Developer/Xcode/DerivedData/SH-PRO-*/Build/Products/Release-iphonesimulator/*.app
