name: Push Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to give the image'
        required: true
        type: string

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf  # v7.2.0
        with:
          context: ./Sources/PushServer
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/ios-pushserver:${{ github.event.inputs.tag }}"
