name: Size build

on:
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 60
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
  HOMEBREW_NO_INSTALL_CLEANUP: TRUE
  BUNDLE_PATH: vendor/bundle

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: "Cache: Pods"
        id: cache_pods
        with:
          path: |
            Pods
            Tools/MaterialDesignIcons.ttf
            Tools/MaterialDesignIcons.json
          key: >-
            ${{ runner.os }}-pods-${{ env.DEVELOPER_DIR }}-
            ${{ hashFiles('**/Gemfile.lock', '**/Podfile.lock', 'Tools/BuildMaterialDesignIconsFont.sh') }}

      - uses: actions/cache@v3
        name: "Cache: Gems"
        id: cache_gems
        with:
          path: vendor/bundle
          key: >-
            ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ env.DEVELOPER_DIR }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Brews
        # right now, we don't need anything from brew for sizing, so save some time
        if: ${{ false }}
        run: brew bundle

      - name: Install Gems
        if: steps.cache_gems.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3

      - name: Install Pods Release
        if: steps.cache_pods.outputs.cache-hit != 'true'
        run: bundle exec pod install --repo-update

      - name: Build app
        run: bundle exec fastlane ios size
        env:
          P12_KEY_IOS_APP_STORE: ${{ secrets.P12_KEY_IOS_APP_STORE }}
          P12_KEY_MAC_APP_STORE: ${{ secrets.P12_KEY_MAC_APP_STORE }}
          P12_KEY_MAC_DEVELOPER_ID: ${{ secrets.P12_KEY_MAC_DEVELOPER_ID }}
          P12_VALUE_IOS_APP_STORE: ${{ secrets.P12_VALUE_IOS_APP_STORE }}
          P12_VALUE_MAC_APP_STORE: ${{ secrets.P12_VALUE_MAC_APP_STORE }}
          P12_VALUE_MAC_DEVELOPER_ID: ${{ secrets.P12_VALUE_MAC_DEVELOPER_ID }}
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_TOKEN }}
          EMERGE_REPO_NAME: ${{ github.repository }}
          EMERGE_PR_NUMBER: ${{ github.event.number }}
          EMERGE_SHA: ${{ github.sha }}
          # hard-coded so it doesn't cause 'ios' to be *** everywhere in the logs
          SENTRY_PROJECT: ios
