import Foundation

/// A believable day of energy data for previews, the complication picker and the snapshot tests:
/// demand peaking morning and evening, generation peaking at midday.
///
/// Fixed to 14 November 2023 so a preview drawn today looks like one drawn next week, and so the
/// recorded snapshot references don't change with the calendar.
public enum EnergyComplicationSampleData {
    public static let dayStart = Calendar.current.startOfDay(for: Date(timeIntervalSince1970: 1_700_000_000))

    /// A home with solar and a grid connection: it uses what it generates and exports the surplus.
    public static let bars: [EnergyComplicationChartBar] = (0 ..< 24).map { hour in
        let flows = flows(atHour: Double(hour))
        return EnergyComplicationChartBar(
            date: dayStart.addingTimeInterval(Double(hour) * 3600),
            solarUsed: min(flows.load, flows.solar),
            gridUsed: max(flows.load - flows.solar, 0),
            gridReturned: max(flows.solar - flows.load, 0)
        )
    }

    /// The same day for a home that also has a battery: it stores the midday surplus instead of
    /// exporting all of it, and gives it back over the evening peak.
    public static let batteryBars: [EnergyComplicationChartBar] = (0 ..< 24).map { hour in
        let h = Double(hour)
        let flows = flows(atHour: h)
        let exported = max(flows.solar - flows.load, 0)
        let fromGrid = max(flows.load - flows.solar, 0)
        let charged = min(exported, h >= 10 && h <= 15 ? 0.9 : 0)
        let discharged = h >= 18 && h <= 22 ? min(fromGrid, 0.7) : 0
        return EnergyComplicationChartBar(
            date: dayStart.addingTimeInterval(h * 3600),
            solarUsed: min(flows.load, flows.solar),
            batteryUsed: discharged,
            // What the battery covered was never drawn from the grid.
            gridUsed: max(fromGrid - discharged, 0),
            batteryCharged: charged,
            // What the battery stored never left the property.
            gridReturned: max(exported - charged, 0)
        )
    }

    /// The figures the sample day adds up to.
    public static var stats: [EnergyComplicationStat] {
        stats(for: bars)
    }

    /// Every series a dashboard can put on the complication, for the layout that has to survive a
    /// home with all of them.
    public static var allSourceStats: [EnergyComplicationStat] {
        stats(for: batteryBars, gas: 4.8)
    }

    /// The figures a set of buckets adds up to, in the widget's order — grid, solar, battery, gas —
    /// skipping any series the buckets don't carry, the way the watch app skips a series the server
    /// doesn't report.
    ///
    /// Derived from the bars rather than written out so a sample's numbers always agree with the
    /// chart drawn under them, whichever shape of dashboard the sample describes. Gas is passed in
    /// because it is never a bar: it is metered in m³ as often as in kWh, so the energy dashboard
    /// gives it a card of its own rather than a series on this chart.
    ///
    /// One assumption, which holds for the sample days and not in general: what left the property
    /// was generated by the panels, so it counts towards the solar figure. A real home can export
    /// from its battery too, and the watch app reads both totals from the server instead of
    /// inferring either.
    public static func stats(
        for bars: [EnergyComplicationChartBar],
        gas: Double? = nil,
        gasUnit: String = "m³"
    ) -> [EnergyComplicationStat] {
        func total(_ value: (EnergyComplicationChartBar) -> Double) -> Double {
            bars.reduce(0) { $0 + value($1) }
        }
        let imported = total { $0.gridUsed }
        let returned = total { $0.gridReturned }
        let generated = total { $0.solarUsed }
        let discharged = total { $0.batteryUsed }
        let charged = total { $0.batteryCharged }

        var figures: [EnergyComplicationStat] = []
        if imported > 0 || returned > 0 {
            // Counted the way the dashboard's "Electricity total" is: drawn from the grid positive.
            figures.append(.energy(.grid, kWh: imported - returned))
        }
        if generated > 0 {
            figures.append(.energy(.solar, kWh: generated + returned))
        }
        if discharged > 0 || charged > 0 {
            // And the battery the other way round, discharge positive, because it is read as
            // something that supplies the home rather than as a bill.
            figures.append(.energy(.batteryOut, kWh: discharged - charged))
        }
        if let gas {
            figures.append(.init(series: .gas, value: quantity(gas), unit: gasUnit))
        }
        return figures
    }

    /// Shorthand for the gas figure's own formatting, which is the one that isn't kWh.
    private static func quantity(_ value: Double) -> String {
        EnergyComplicationStat.quantity(value)
    }

    /// One hour of the sample day: household demand peaks in the morning and again in the evening,
    /// generation peaks at midday.
    private static func flows(atHour h: Double) -> (load: Double, solar: Double) {
        let load = 0.25 + 0.8 * exp(-pow(h - 7, 2) / 4) + 1.0 * exp(-pow(h - 20, 2) / 6)
        let solar = h >= 6 && h <= 18 ? 1.6 * sin((h - 6) / 12 * .pi) : 0
        return (load, solar)
    }
}
